language: ruby
rvm:
  - 2.1.1
script:
  - RAILS_ENV=test bundle exec rake db:schema:load --trace
  - bundle exec rspec
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database g5_hub_test;' -U postgres
notifications:
  campfire:
    rooms:
      secure: ZajSlUQKuUK6LnLIaPFEfITUS+w6UCAUqnaZnWQBq+976lR0ajhkxOx4Azr9DYTSC4EVpqV948xLTbnpBXCKhNGU70L1/C6cH71oreGW+u+9yCtGC8OskZtYUZrli6bDn2skIjNeFsO0Z7w4SC3uAHL6KnhPBiAKJGFYzNDCV8A=
    template:
      - "%{repository}#%{build_number} %{message} (%{branch} - %{commit} : %{author}) Change view : %{compare_url} Build details : %{build_url}"
    on_success: change
    on_failure: always
